---
title: "Tesis_JG"
author: "Julio Gutiérrez"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Juntando data

```{r}

#install.packages("foreign")
library(foreign)
getwd()

setwd("C:/Users/julgutierrez/OneDrive - International Organization for Migration - IOM/Personal documents/MAESTRIA/Tesis/DB - ENPOVE")

modulo1 <- read.spss("ENPOVE_Capitulo 100 - Carctaerísticas de la Vivienda y del Hogar.sav.sav", to.data.frame = T)


modulo2 <- read.spss("ENPOVE_Capitulo 200 - Carctaerísticas de los Residentes del Hogar.sav.sav", to.data.frame = T)
modulo2$COD_UNICO=paste0(modulo2$UBIGEO, modulo2$ZONA, modulo2$VIVIENDA, modulo2$HOGAR, modulo2$CODPERSO)

modulo3 <- read.spss("ENPOVE_Capitulo 300 - Situación Migratoria de la Persona.sav.sav", to.data.frame = T)
modulo3$COD_UNICO=paste0(modulo3$UBIGEO, modulo3$ZONA, modulo3$VIVIENDA, modulo3$HOGAR, modulo3$CODPERSO)
#P304

modulo4 <- read.spss("ENPOVE_Capitulo 400 - Salud.sav.sav", to.data.frame = T)
modulo4$COD_UNICO=paste0(modulo4$UBIGEO, modulo4$ZONA, modulo4$VIVIENDA, modulo4$HOGAR, modulo4$CODPERSO)
#P401

modulo5 <- read.spss("ENPOVE_Capitulo 500 - Educación(cambio).sav.sav", to.data.frame = T)
modulo5$COD_UNICO=paste0(modulo5$UBIGEO, modulo5$ZONA, modulo5$VIVIENDA, modulo5$HOGAR, modulo5$CODPERSO)
#P510 y Nivel de educación

modulo6 <- read.spss("ENPOVE_Capitulo 600 - Empleo(cambio).sav.sav", to.data.frame = T)
modulo6$COD_UNICO=paste0(modulo6$UBIGEO, modulo6$ZONA, modulo6$VIVIENDA, modulo6$HOGAR, modulo6$CODPERSO)

modulo7 <- read.spss("ENPOVE_Capitulo 700 - Discriminación.sav.sav", to.data.frame = T)
modulo7$COD_UNICO=paste0(modulo7$UBIGEO, modulo7$ZONA, modulo7$VIVIENDA, modulo7$HOGAR, modulo7$CODPERSO)

#data final 
#install.packages("plyr")
library(plyr)

#merge data
#df <- join_all(list(modulo2,modulo3,modulo4,modulo5, modulo6, modulo7),by = 'COD_UNICO', type = 'full')

```
CREACION DE VARIABLES
```{r}
library(dplyr)

residentes=modulo2[,c("COD_UNICO", "P204", "P205_A", "P206")]

names(residentes)[names(residentes)=="P204"]="Sexo"
names(residentes)[names(residentes)=="P205_A"]="Edad"
names(residentes)[names(residentes)=="P206"]="Estado_civil"

residentes$Estado_civil=recode(residentes$Estado_civil, 'Conviviente'='con pareja','Casado/a'='con pareja','Viudo/a'='sin pareja', 'Divorciado/a'='sin pareja','Separado/a o Ex conviviente'='sin pareja', 'Soltero/a'='sin pareja' )

residentes$Sexo=as.factor(residentes$Sexo)
residentes$Estado_civil=as.factor(residentes$Estado_civil)
##residentes$Edad=recode(residentes$Edad, "lo:13='nino', 14-26='joven', 27-59='adulto', 60:hi='adulto mayor'")## SALE NA otra vez


situacion=modulo3[, c("COD_UNICO","P304", "CIUDADES_DE_ESTUDIO", "NOMBDEPA" ,"P303_A")]
names(situacion)[names(situacion)=="P304"]="Calidad_migratoria"
names(situacion)[names(situacion)=="P303_A"]="Tiempo_Residencia"
names(situacion)[names(situacion)=="CIUDADES_DE_ESTUDIO"]="Zona"
names(situacion)[names(situacion)=="NOMBDEPA"]="Departamento"

situacion$Calidad_migratoria=recode(situacion$Calidad_migratoria, 'Si'='regular', 'No'='irregular')

Variables_demo=merge(residentes, situacion, by.y="COD_UNICO", by.x = "COD_UNICO")

```
ACCEESO AL MERCADO LABORAL 
```{r}
#P601, P602, P603, P608 / Desempleado --> NO , 601, 602, 603 
#trabajador independiente --> 608 (1,2)
#trabajador dependiente --> 608, (resto)

#VARIABLES DE EMPLEO
Empleo=modulo6[,c("COD_UNICO","CODIGO_HOGAR" ,"Desempleo_1","P608", "P614_ESP", "P614_MON","P615_ESP","P615_MON","P616_ESP", "P616_MON", "P609")]
Empleo$COD_UNICO=gsub(" ",'',Empleo$COD_UNICO)
Empleo$CODIGO_HOGAR=trimws(Empleo$CODIGO_HOGAR, whitespace = "[\\h\\v]")

#VARIABLE TIPO DE EMPLEO

Empleo$P608=recode(Empleo$P608,
                   '¿Empleador o patrono?'='independiente',
                   '¿Trabajador independiente?'='independiente',
                   '¿Empleado?'='dependiente', 
                   '¿Obrero?'='dependiente',
                   '¿Trabajador familiar no remunerado?'='dependiente',
                   '¿Trabajador del hogar?'='dependiente',
                   '¿Otro?'='dependiente')

Empleo$Tipo_Empleo=paste0(Empleo$Desempleo_1, Empleo$P608)


Empleo$Tipo_Empleo=recode(Empleo$Tipo_Empleo,
                          '0dependiente'='dependiente',
                          '1dependiente'='dependiente',
                          '0independiente'='independiente', 
                          '1independiente'='independiente',
                          '1NA'='desempleado')
Empleo$Tipo_Empleo=as.factor(Empleo$Tipo_Empleo)

#VARIABLE NIVEL DE INGRESO 

Empleo[,5:10]=lapply(Empleo[,5:10],as.numeric)

#install.packages("imputeTS")
library(imputeTS)
Empleo[,5:10] <- na.replace(Empleo[,5:10], 0)# OJO CON ESTO

Empleo$Suma1=Empleo$P614_ESP+Empleo$P614_MON
Empleo$Suma2=Empleo$P615_ESP+Empleo$P615_MON
Empleo$Suma3=Empleo$P616_ESP+Empleo$P616_MON
Empleo$Suma4=Empleo$Suma2+Empleo$Suma3
Empleo$Suma_Final=Empleo$Suma1+Empleo$Suma4

#Empleo$Ingresos=recode(Empleo$Suma_Final, lo:930 ='bajo', 930:1860='medio', 1861:2790='medio-alto', 2791:hi= 'alto') ##Esto no corre

#VARIBALE CONTRATO LABORAL

names(Empleo)[names(Empleo)=="P609"]="Contrato"

Empleo=Empleo[c("COD_UNICO","CODIGO_HOGAR","Tipo_Empleo", "Suma_Final", "Contrato")]

```
EDUCACION
```{r}
Educacion=modulo5[,c("COD_UNICO", "Nivel_educacion", "P510")]
names(Educacion)[names(Educacion)=="P510"]="Certificado" ## Caterorizado como SI/No
Educacion$COD_UNICO=gsub(" ",'', Educacion$COD_UNICO)

Educacion$Nivel_educacion=recode(Educacion$Nivel_educacion, '1'='Sin educacion basica', '2'='Con educacion basica', '3'='Estudios superiores completos')

Educacion[,c(2:3)]=lapply(Educacion[, c(2:3)], as.factor)
```
INCLUSION SOCIAL 
```{r}
#modulo4 y modulo1
salud=modulo4[,c("COD_UNICO","CODIGO_HOGAR","ESTRATO_SOCIOECONOMICO", "P401_5")]
names(salud)[names(salud)=="P401_5"]="Seguro"

salud$Seguro=recode(salud$Seguro, 'NO ESTA AFILIADO'='No', '0'='Si')
salud$Seguro=as.factor(salud$Seguro)


Vivienda=modulo1[, c("CODIGO_HOGAR", "P108")]
names(Vivienda)[names(Vivienda)=="P108"]="Tipo_vivienda"

Vivienda$Tipo_vivienda=recode(Vivienda$Tipo_vivienda, 'Alquilada?'='alquilada', 'Hogar temporal?'='otro','Cedida por otro hogar?'= 'otro','Vivienda propia?'='vivienda propia', 'Albergue?'='otro', 'Otro?'='otro')

Inclusion = merge(salud, Vivienda, all.x=T, all.y=T )

Num_Personas= table(Inclusion$CODIGO_HOGAR)
Num_Personas=as.data.frame(Num_Personas)
names(Num_Personas)[names(Num_Personas)=="Var1"]="CODIGO_HOGAR"
names(Num_Personas)[names(Num_Personas)=="Freq"]="num_personas"
Num_Personas$num_personas=as.numeric(Num_Personas$num_personas)
 
Inclusion_Social=merge(Inclusion, Num_Personas, all.x=T, all.y=T )

#VARIABLE RIESGO DE POBREZA 
Pobreza=aggregate(cbind(Suma_Final ) # dependientes
          ~ CODIGO_HOGAR, # nivel
          data = Empleo,    # data
          sum)
Pobreza=merge(Pobreza, Num_Personas, all.x = T, all.y = T)
Pobreza$Riesgo_pobreza=Pobreza$Suma_Final/Pobreza$num_personas
Pobreza[, 2:3]=NULL

Inclusion_Social=merge(Pobreza,Inclusion_Social, all.x = T, all.y = T)
```

COMUNIDAD ACOGIDA
```{r}
Comunidad=modulo7[,c("COD_UNICO", "P701", "P703", "P707_9")]
names(Comunidad)
names(Comunidad)[names(Comunidad)=="P701"]="Discriminacion"
names(Comunidad)[names(Comunidad)=="P703"]="Ayuda_Inst"
names(Comunidad)[names(Comunidad)=="P707_9"]="Participacion"

Comunidad$Participacion=recode(Comunidad$Participacion,' NO PARTICIPA'='No','0'='Si')

Comunidad[2:4]=lapply(Comunidad[2:4],as.factor)
```
UNION DE BASES
```{r}
df_1 <- join_all(list(Variables_demo,Empleo,Educacion,Inclusion_Social, Comunidad),by = 'COD_UNICO', type = 'full')
df_1=df_1[df_1$Edad >= 14,]
str(df_1)
```
BASE SOLO CON ZONA DE LIMA, EDAD, TIEMPO DE RESIDENCIA EN PERÚ, INGRESOS ECONÓMICOS, CANTIDAD DE INTEGRANTES DEL HOGAR.
```{r}
#Variables_demo -->Edad, Tiempo_Residencia, Zona
#Empleo --> Suma_Final(Ingresos)
#Inclusion_Social --> num_personas (cantidad de integrantes del hogar)
library(plyr)
df_2<- join_all(list(Variables_demo,Empleo,Inclusion_Social),by = 'COD_UNICO', type = 'full')
df_2=df_2[, c("COD_UNICO","Nivel_educacion", "Tiempo_Residencia","Tipo_vivienda","Zona","Tipo_empleo","Contrato", "Suma_Final", "num_personas", "Departamento", "Sexo", "Edad", "Estado Civil", "ESTRATO_SOCIOECONOMICO","Riesgo_pobreza","Discriminacion","num_personas")]


base1 <- data.frame (Ano_actual=c (2020), PANO=c(2018)) 
base2=modulo2[, c("COD_UNICO","PANO")]
base3=merge(base1, base2, by.y="PANO", by.x="PANO")
base3$PANO=NULL
str(base3)

df_2=merge(df_2, base3, by.x = "COD_UNICO", by.y="COD_UNICO")
df_2$Tiempo_Residencia=df_2$Ano_actual-df_2$Tiempo_Residencia
df_2$Ano_actual=NULL

df_2$Departamento=trimws(df_2$Departamento, whitespace = "[\\h\\v]")
df_2$Departamento=as.factor(df_2$Departamento)
df_2=df_2[df_2$Departamento=="LIMA",]
df_2=df_2[df_2$Edad >= 14,]
```

```{r}
#Export XLSX

library(readxl)
library(openxlsx)
setwd("/cloud/project") ##ubicación del archivo
write.xlsx(df_2, file = "/cloud/project/ENPOVE_LIMA_2.xlsx")#export xlsx
```



